name: CI

on: [push]

jobs:
  build:
    name: do the build.
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Run build script
      shell: pwsh
      run: ./build.ps1
    - uses: actions/upload-artifact@master
      with:
        name: TestGitHubActionsApp
        path: ./out
